import fs from 'node:fs'
import path from 'node:path'
import { defineConfig } from 'vitepress'
import callouts from './plugins/callouts.js'
// Generated by scripts/build-content.mjs from the published entries (categories as groups).
import sidebar from '../.content/_data/sidebar.json'

const SITE = 'https://knowledge.irfanmim.com'
const SITE_NAME = 'Knowledge Base'
const SITE_DESCRIPTION = 'What I know about software engineering, organized by topic.'
const OG_IMAGE = `${SITE}/og-default.png`
const escapeAttr = (s: string) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

// 'system-design/rate-limiter.md' -> '/system-design/rate-limiter'; folder indexes keep the trailing slash.
const pagePath = (relativePath: string) => {
  const p = '/' + relativePath.replace(/\.md$/, '')
  return p === '/index' ? '/' : p.replace(/\/index$/, '/')
}
const sitemapKey = (url: string) => url.replace(/^\/+|\/+$/g, '').replace(/\.html$/, '')

// Collected while pages render, used for <lastmod> in the sitemap (built afterwards).
const lastmods = new Map<string, string>()

export default defineConfig({
  title: SITE_NAME,
  titleTemplate: `:title | ${SITE_NAME}`,
  description: SITE_DESCRIPTION,
  lang: 'en',
  // Built from the staging folder produced by scripts/build-content.mjs, never from vault/ directly.
  srcDir: '.content',
  cleanUrls: true,
  lastUpdated: false,
  sitemap: {
    hostname: SITE,
    transformItems: (items) =>
      items.map((item) => {
        const lastmod = lastmods.get(sitemapKey(item.url))
        return lastmod ? { ...item, lastmod: new Date(lastmod + 'T00:00:00Z').getTime() } : item
      }),
  },
  transformPageData(pageData) {
    const { frontmatter, relativePath } = pageData
    if (frontmatter.status && frontmatter.updated) lastmods.set(sitemapKey(pagePath(relativePath)), String(frontmatter.updated))
  },
  // Canonical URL, Open Graph / Twitter tags and (for entries) Article JSON-LD, per page.
  transformHead({ pageData }) {
    const { frontmatter: fm, relativePath } = pageData
    const url = SITE + pagePath(relativePath)
    const isEntry = !!fm.status && !fm.isCategory && !fm.isTag
    const title = String(pageData.title || SITE_NAME)
    const description = String(fm.description || pageData.description || SITE_DESCRIPTION)

    const head: [string, Record<string, string>, string?][] = [
      ['link', { rel: 'canonical', href: url }],
      ['meta', { property: 'og:site_name', content: SITE_NAME }],
      ['meta', { property: 'og:type', content: isEntry ? 'article' : 'website' }],
      ['meta', { property: 'og:title', content: title }],
      ['meta', { property: 'og:description', content: description }],
      ['meta', { property: 'og:url', content: url }],
      ['meta', { property: 'og:image', content: OG_IMAGE }],
      ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ]
    if (isEntry) {
      head.push(['meta', { property: 'article:published_time', content: String(fm.date) }])
      head.push(['meta', { property: 'article:modified_time', content: String(fm.updated) }])
      for (const tag of fm.tags ?? []) head.push(['meta', { property: 'article:tag', content: String(tag) }])
      const ld = {
        '@context': 'https://schema.org',
        '@type': 'Article',
        headline: title,
        description,
        datePublished: fm.date,
        dateModified: fm.updated,
        mainEntityOfPage: url,
        image: OG_IMAGE,
        author: { '@type': 'Person', name: 'irfanmim', url: 'https://irfanmim.com' },
      }
      head.push(['script', { type: 'application/ld+json' }, JSON.stringify(ld).replace(/</g, '\\u003c')])
    }
    return head
  },
  head: [
    // Same favicon as irfanmim.com (copied from personal-website-fe/public/favicon.svg)
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    [
      'link',
      {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap',
      },
    ],
  ],
  markdown: {
    // Obsidian callouts are handled by our own plugin (custom titles, folding, more types).
    gfmAlerts: false,
    config: (md) => md.use(callouts),
  },
  vite: {
    // Set by the backend's docker-compose.yml: bind mounts don't deliver file events.
    server: { watch: process.env.USE_POLLING === 'true' ? { usePolling: true } : undefined },
  },
  // Old URLs of renamed entries (front matter `redirect_from`) get a small redirect page.
  buildEnd(siteConfig) {
    const file = path.join(siteConfig.srcDir, '_data', 'redirects.json')
    if (!fs.existsSync(file)) return
    const redirects: Record<string, string> = JSON.parse(fs.readFileSync(file, 'utf8'))
    for (const [from, to] of Object.entries(redirects)) {
      const dest = path.join(siteConfig.outDir, from + '.html')
      fs.mkdirSync(path.dirname(dest), { recursive: true })
      fs.writeFileSync(
        dest,
        `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Redirecting…</title>` +
          `<meta name="robots" content="noindex"><link rel="canonical" href="${escapeAttr(SITE + to)}">` +
          `<meta http-equiv="refresh" content="0; url=${escapeAttr(to)}"></head>` +
          `<body><a href="${escapeAttr(to)}">Moved here</a></body></html>\n`,
      )
    }
  },
  themeConfig: {
    nav: [
      { text: 'Tags', link: '/tags/' },
      { text: 'irfanmim.com', link: 'https://irfanmim.com' },
    ],
    // Local search indexes only .content/, i.e. published entries. Listing pages set `search: false`.
    search: {
      provider: 'local',
      options: { translations: { button: { buttonText: 'Search entries', buttonAriaLabel: 'Search entries' } } },
    },
    sidebar,
    outline: { level: [2, 3], label: 'On this page' },
  },
})
